### ISSUE TITLE
JS functions/callbacks don't work for the JS FFI

### ISSUE THREAD

**Issue by Risto-Stevcev** [idris-lang/Idris-dev#3899]
I tried running this code snippet:
https://github.com/idris-lang/Idris-dev/blob/edf03eebbc7010a1ce74127e79fd60737e327006/test/ffi010/ffi010.idr

and got:
```
/home/risto/git/idris/idris-asyncio/ex.js:79
        i$CALL(_idris__123_APPLY0_125_,[oldbase])
               ^

ReferenceError: _idris__123_APPLY0_125_ is not defined
    at /home/risto/git/idris/idris-asyncio/ex.js:79:16
    at _idris_Main_46_call_95_fn (/home/risto/git/idris/idris-asyncio/ex.js:174:67)
    at i$RUN (/home/risto/git/idris/idris-asyncio/ex.js:113:10)
    at main (/home/risto/git/idris/idris-asyncio/ex.js:558:3)
    at Object.<anonymous> (/home/risto/git/idris/idris-asyncio/ex.js:560:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I've also tried running some of the IdrisScript code that has callbacks, like `setTimeout`, and it also either fails silently or does something similar to the above. The issue seems to be related to JS functions in particular. I ran this on v1.0

**Comment by clayrat** [comment]
Looks like a duplicate of https://github.com/idris-lang/Idris-dev/issues/3742

**Comment by Risto-Stevcev** [comment]
@clayrat Yeah it's the same issue, thanks for finding it and sorry about that. I thought I looked at all related issues but I missed that one
