### ISSUE TITLE
New JS codegen leaving code out during compilation

### ISSUE THREAD

**Issue by Risto-Stevcev** [idris-lang/Idris-dev#3923]
I'm trying to generate the commented out code here:
https://github.com/Risto-Stevcev/idris-node-fs/blob/master/Test/FileSystem.idr#L32-L36

But the compiled js file is producing the following runtime error:
```
/home/risto/git/idris/idris-node-fs/testit:764
    return $partial_5_6$io_95_bind(null, null, null, Control__Monad__Free__foldFree($HC_0_65647$Unit, Node__Free__FileSystem__FileSystemF, null, new $HC_2_0$Prelude__Monad__Monad_95_ictor(new $HC_3_0$Prelude__Applicative__Applicative_95_ictor($partial_0_1$Test__FileSystem__Main___123_main_95_3_125_(), $partial_0_1$Test__FileSystem__Main___123_main_95_5_125_(), $partial_0_1$Test__FileSystem__Main___123_main_95_9_125_()), $partial_0_1$Test__FileSystem__Main___123_main_95_13_125_()), null, $partial_0_1$Test__FileSystem__Main___123_main_95_14_125_(), Test__FileSystem__exclaimHello()), $partial_0_1$Test__FileSystem__Main___123_main_95_30_125_());
                                                                                                      ^

ReferenceError: Node__Free__FileSystem__FileSystemF is not defined
    at Test__FileSystem__Main__main (/home/risto/git/idris/idris-node-fs/testit:764:103)
    at $_0_runMain (/home/risto/git/idris/idris-node-fs/testit:1339:25)
    at Object.<anonymous> (/home/risto/git/idris/idris-node-fs/testit:1354:1)
    at Object.<anonymous> (/home/risto/git/idris/idris-node-fs/testit:1355:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```
I'm using [this library](https://github.com/Risto-Stevcev/idris-naps) I wrote to manage deps, it's just a convenient wrapper to run some idris commands. So I ran `naps --install-deps`, which just installs all the idris libs it needs into the `libs` folder of the project root directory, and uses that as the IDRIS_LIBRARY_PATH for commands.

I ran this command to generate the js file:
```
PATH=/home/risto/git/idris/idris-dev/dist/build/idris-codegen-node:$PATH IDRIS_BINARY_PATH=/home/risto/git/idris/idris-dev/dist/build/idris/idris naps --codegen node Test/FileSystem.idr -o testit
```

which is actually running this under the hood:
```
PATH=/home/risto/git/idris/idris-dev/dist/build/idris-codegen-node:$PATH IDRIS_LIBRARY_PATH=/home/risto/git/idris/idris-node-fs/libs home/risto/git/idris/idris-dev/dist/build/idris/idris -i /home/risto/git/idris/idris-node-fs/libs/idris_async -i /home/risto/git/idris/idris-node-fs/libs/idris_free -i /home/risto/git/idris/idris-node-fs/libs/idris_jserror -i /usr/share/idris/libs/base -i /usr/share/idris/libs/contrib -i /usr/share/idris/libs/effects -i /usr/share/idris/libs/prelude -i /usr/share/idris/libs/pruviloj --codegen node Test/FileSystem.idr -o testit
```

It seems like idris isn't bringing in `FileSystemF` from `Node.Free.FileSystem`, even though it's imported in `Test.FileSystem`. The old backend doesn't have this import issue, but it has a [separate issue](https://github.com/idris-lang/Idris-dev/issues/3742) where it doesn't run async code properly (the sync code in this test module works fine with the old backend), so I need to use the new backend for this.

What might be causing this issue?

**Comment by rbarreiro** [comment]
Can you reduce the example as much as you can? delete code and merge modules as long as the error persists? Or does it go away when you remove anything? Anyway, can you provide the list of necessary commands to build the example?

**Comment by Risto-Stevcev** [comment]
Sorry, I should've provided a more minimal example earlier. You can replicate it by running the following sequence of commands:

```bash
git clone git@github.com:Risto-Stevcev/idris-node-fs.git
cd idris-node-fs
bower install
mkdir libs

cd bower_components/idris-free
IDRIS_LIBRARY_PATH=$(realpath $(pwd)/../..)/libs idris -i /usr/share/idris/libs/prelude --install idris-free.ipkg

cd ../idris-jserror
IDRIS_LIBRARY_PATH=$(realpath $(pwd)/../..)/libs idris -i /usr/share/idris/libs/prelude --install idris-jserror.ipkg

cd ../idris-async
IDRIS_LIBRARY_PATH=$(realpath $(pwd)/../..)/libs idris -i /usr/share/idris/libs/prelude --install idris-async.ipkg

cd ../..
IDRIS_LIBRARY_PATH=$(pwd)/libs idris -i /usr/share/idris/libs/prelude -i $(pwd)/libs/idris_free -i $(pwd)/libs/idris_async -i $(pwd)/libs/idris_jserror --codegen node Test/FileSystem.idr -o testit
```

That last command might be a little different for you depending on how you have idris set up. My package manager has v1.0 so it doesn't have the new backend. I have to use the binary from this repo so that I can use the new backend, so I run this instead:

```bash
IDRIS_LIBRARY_PATH=$(pwd)/libs PATH=/home/risto/git/idris/idris-dev/dist/build/idris-codegen-node:$PATH /home/risto/git/idris/idris-dev/dist/build/idris/idris -i /usr/share/idris/libs/prelude -i $(pwd)/libs/idris_free -i $(pwd)/libs/idris_async -i $(pwd)/libs/idris_jserror --codegen node Test/FileSystem.idr -o testit
```

**Comment by Risto-Stevcev** [comment]
Hmm that's really odd... I inlined and flattened every single module into just one large file:
https://gist.github.com/Risto-Stevcev/4230935939bb792675e30c0d3679d7ed

and ran the simplest codegen command:
```bash
PATH=/home/risto/git/idris/idris-dev/dist/build/idris-codegen-node:$PATH /home/risto/git/idris/idris-dev/dist/build/idris/idris --codegen node Test/FileSystem.idr -o testit
```

and it's still giving the same error:
```
ReferenceError: Main__FileSystemF is not defined
    at Main__main (/home/risto/git/idris/idris-test/idris-node-fs/testit:667:160)
    at $_0_runMain (/home/risto/git/idris/idris-test/idris-node-fs/testit:1135:25)
    at Object.<anonymous> (/home/risto/git/idris/idris-test/idris-node-fs/testit:1150:1)
    at Object.<anonymous> (/home/risto/git/idris/idris-test/idris-node-fs/testit:1151:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

I was convinced that it was a module issue because it was leaving out the code. It seems like a pretty ordinary boring ADT, what makes it so special?

**Comment by rbarreiro** [comment]
I am not sure, but I suspect that the constructor is appearing in the LDecls intermediate representation as (LV(LGlob <name>)) and I was expecting all constructors to be on an LCon, because that was all that I had seen.
I will investigate further.

**Comment by rbarreiro** [comment]
@Risto-Stevcev  What is the expected output?

**Comment by Risto-Stevcev** [comment]
@rbarreiro for that gist I posted, it should just read `foo.txt` and output it's contents to stdout

**Comment by Risto-Stevcev** [comment]
The `foo.txt` is a relative path, so it's whatever is in `./foo.txt` from the current working directory of where the program is running

**Comment by rbarreiro** [comment]
I was able to reduce the example a bit. 

```idris
module Main

data Free : (f : Type -> Type) -> (a : Type) -> Type where
  Pure : a -> Free f a
  Bind : f (Free f a) -> Free f a

Functor f => Functor (Free f) where
  map f m = assert_total $ case m of
    Pure x => Pure (f x)
    Bind x => Bind (map (map f) x)

Functor f => Applicative (Free f) where
  pure = Pure

  m <*> x = assert_total $ case m of
    Pure f => map f x
    Bind f => Bind (map (<*> x) f)

Functor f => Monad (Free f) where
  m >>= f = assert_total $ case m of
    Pure x => f x
    Bind x => Bind (map (>>= f) x)

liftFree : Functor f => f a -> Free f a
liftFree = assert_total $ Bind . map Pure

foldFree : (Monad m, Functor f) => ({ a : Type } -> f a -> m a) -> Free f b -> m b
foldFree f m = assert_total $ case m of
  Pure x => pure x
  Bind x => f x >>= foldFree f

data FileSystemF next
  = ReadFile (String -> next)

FileSystem : Type -> Type
FileSystem = Free FileSystemF

Functor FileSystemF where
  map f (ReadFile nextFn) = ReadFile (f . nextFn)

readFileF : FileSystem String
readFileF = liftFree $ ReadFile id



interpret2 : FileSystemF a -> JS_IO a
interpret2 (ReadFile nextFn) = do
  contents <- pure "ola"
  pure (nextFn contents)

main : JS_IO ()
main =
  do
    c <- foldFree interpret2 readFileF
    putStr' c
```

**Comment by Risto-Stevcev** [comment]
@rbarreiro that example runs fine for me, it doesn't produce the runtime error

**Comment by melted** [comment]
In addition to the fix, it would be nice to add a test case for this.

**Comment by rbarreiro** [comment]
I might be messing something up but this example blows up for me, can someone else check it?

**Comment by rbarreiro** [comment]
@Risto-Stevcev  I made a PR #3930, can you check if it solves it for you?

**Comment by rbarreiro** [comment]
@Risto-Stevcev Are you checking this example with master or with v1.0?

**Comment by rbarreiro** [comment]
@melted the test should be added after the fix is merged right?

**Comment by melted** [comment]
That's ok

**Comment by Risto-Stevcev** [comment]
@rbarreiro  I was checking it with master. The PR works! the program is running as expected :slightly_smiling_face:
