### ISSUE TITLE
Improving runtime error messages for non-exhaustive patterns in partial functions

### ISSUE THREAD

**Issue by robstewart57** [idris-lang/Idris-dev#4220]
Executing partial functions in compiled programs can fail with a segfault.

Take this partial function:

    fPartial : Vect 1 (Maybe Nat) -> Nat
    fPartial = sum . map (\(Just x) => div x 2)

    main : IO ()
    main = print (fPartial [Nothing])

Running this:

    ./test                
    segmentation fault (core dumped)  ./test

As programs scale, possibly with partial functions in multiple locations, it'd be good to know which of those causes a segfault.

Inlining the definition of sum using foldr:

    fPartial = foldr (+) 0 (map (\(Just x) => div x 2)

Obtaining a backtrace with gdb shows that the segfault occurs by trying to apply the (+) operation, which is meaningless on the `Nothing` value from the `main` function (spot `_idris_Data_46_Vect_46_foldrImpl` and `__gmpz_add` symbols):

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff7b65114 in __gmpz_add () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
    (gdb) backtrace 
    #0  0x00007ffff7b65114 in __gmpz_add () from /usr/lib/x86_64-linux-gnu/libgmp.so.10
    #1  0x000055555556177c in bigAdd ()
    #2  0x000055555555b8ee in _idris_Main_46__123_fPartial_95_0_125_ (vm=0x55555576b260, oldbase=0x7ffff5615050) at /tmp/idris10227-0.c:1221
    #3  0x000055555555aa5b in _idris__123_APPLY_95_0_125_ (vm=0x55555576b260, oldbase=0x7ffff5615050) at /tmp/idris10227-0.c:1033
    #4  0x0000555555556531 in _idris_Prelude_46_Basics_46__46_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:131
    #5  0x000055555555ae89 in _idris__123_APPLY_95_0_125_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:1086
    #6  0x0000555555556f96 in _idris_Data_46_Vect_46_foldrImpl (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:237
    #7  0x0000555555556ee0 in _idris_Data_46_Vect_46_foldrImpl (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:227
    #8  0x000055555555caaa in _idris_Main_46__123_fPartial_95_2_125_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:1418
    #9  0x000055555555ab81 in _idris__123_APPLY_95_0_125_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:1049
    #10 0x00005555555565fc in _idris_Prelude_46_Basics_46__46_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:138
    #11 0x000055555555ae89 in _idris__123_APPLY_95_0_125_ (vm=0x55555576b260, oldbase=0x7ffff5615020) at /tmp/idris10227-0.c:1086
    #12 0x0000555555557968 in _idris_Main_46_main (vm=0x55555576b260, oldbase=0x7ffff5615010) at /tmp/idris10227-0.c:363
    #13 0x000055555555c0e4 in _idris__123_runMain_95_0_125_ (vm=0x55555576b260, oldbase=0x0) at /tmp/idris10227-0.c:1314
    #14 0x000055555555e70b in main (argc=1, argv=0x7fffffffda68) at /tmp/idris10227-0.c:1897

The problem with this debugging approach to find the erroneous partial function in my potentially large program, is that I don't know which `foldr` in which partial function is causing the segfault.

Since Idris is strict, why has the evaluation of `foldrImpl` begun before the non-exhaustive pattern in `fPartial` detected by attempting to reduce it to a vector of `div x 2` results first?

How invasive would the change be to the Idris RTS, to improve the runtime error message that would otherwise be segfaults? E.g.

from

    ./test                
    segmentation fault (core dumped)  ./test

to

    ./test
    test:2 : non-exhaustive patterns in lambda in fPartial

**Comment by ahmadsalim** [comment]
Thanks for the feature request.
As always, we value PRs!
